#!/bin/bash

# Configuration des couleurs
GREEN='\033[0;32m'
NC='\033[0m'
BOLD='\033[1m'

# Tableau des 50 scénarios de test pour le RAG (Server Administration)
QUESTIONS=(
    # III.16 & 17. Installation (Binaries & Source Code)
    "What are the mandatory prerequisite packages and libraries required to compile PostgreSQL from source code?"
    "How can I specify a custom installation directory prefix during the source code configuration phase?"
    "What is the standard purpose of the --with-ssl=openssl flag when executing the ./configure script?"
    "In a binary-based installation on Debian/Ubuntu, which package contains the standard server binaries like postgres and initdb?"
    "How do you compile only the PostgreSQL documentation from a source tree install?"

    # III.18. Server Setup and Operation
    "/a minimal required arguments for the initdb command to initialize a secure data directory with a custom superuser"
    "/a safely start the PostgreSQL server in the background using pg_ctl instead of direct postgres execution"
    "What happens internally when a PostgreSQL server receives a SIGINT (Fast Shutdown) signal via pg_ctl stop -m fast?"
    "/a show me the current data_directory path"
    "What is the risk of running the initdb utility as the operating system root user?"

    # III.19. Server Configuration
    "What is the difference between changing a parameter in postgresql.conf that requires a server restart versus one that only requires a reload?"
    "/a check which parameters in pg_settings have been modified from their default values"
    "What is the recommended formula or approach to calculate an optimal value for shared_buffers on a dedicated database server?"
    "/a change the max_connections parameter to '150'"
    "/a modify shared_buffers to '512MB'"
    "/a add an invalid line to postgresql.conf with missing quotes"
    "What is the exact purpose of the include_dir directive inside the main postgresql.conf file?"

    # III.20. Client Authentication
    "How does the order of entries in the pg_hba.conf file affect how a client connection is evaluated?"
    "What is the security difference between the trust and md5/scram-sha-256 authentication methods in pg_hba.conf?"
    "/a configure pg_hba.conf to allow only local connections using Unix domain sockets via trust authentication"
    "What specific steps and configuration parameters are required to enforce mandatory TLS/SSL for all remote client connections?"
    "/a open the pg_hba.conf file using vi to see the contents"

    # III.21. Database Roles
    "What is the functional difference between a PostgreSQL ROLE created with LOGIN attributes versus one created with NOLOGIN?"
    "How does the inherit attribute affect how a member role receives permissions from a parent group role?"
    "/a grant read-only access to all current and future tables within a specific schema"
    "Explain the security implications and use cases of the REPLICATION privilege on a database role"
    "How can a superuser temporarily drop their elevated privileges to execute commands under a specific standard user context?"

    # III.22. Managing Databases
    "What is the underlying template database used by default when executing the CREATE DATABASE command?"
    "/a prevent new connections to a specific database while preparing to drop it"
    "What happens to physical disk storage and files when a DROP DATABASE command is successfully executed?"
    "/a rename an existing active database without causing data corruption"
    "/a get database status"

    # III.23. Localization
    "How do LC_COLLATE and LC_CTYPE settings impact index creation and text sorting behaviors after cluster initialization?"
    "Can you modify the character set encoding (e.g., changing from SQL_ASCII to UTF8) of an existing database without recreating it?"

    # III.24. Routine Database Maintenance Tasks
    "What are the new specific parameters introduced in PostgreSQL 18 for vacuum?"
    "What are the three primary symptoms or issues that the VACUUM process solves in a PostgreSQL MVCC environment?"
    "What is the fundamental operational difference between a standard VACUUM and a VACUUM FULL command regarding table locking?"
    "How does the ANALYZE command assist the cost-based query planner, and how is it different from VACUUM?"
    "Explain how the autovacuum daemon determines exactly when a specific table needs to be vacuumed or analyzed automatically."
    "What is transaction ID wraparound, and how does PostgreSQL prevent data loss using aggressive maintenance?"

    # III.25. Backup and Restore
    "What is the difference between a logical backup using pg_dump versus a physical backup using pg_basebackup?"
    "/a perform a parallelized backup of a large database using pg_dump and specify custom format"
    "/a restore a custom-format .dump file generated by pg_dump using the pg_restore utility"
    "To perform Point-in-Time Recovery (PITR), what parameters must be configured in postgresql.conf to enable continuous WAL archiving?"
    "How do you specify the target recovery timestamp or transaction ID during a physical PITR restore process?"

    # III.26. High Availability, Load Balancing, and Replication
    "What is the mechanical difference between synchronous physical replication and asynchronous physical replication?"
    "/a create a physical replication slot named test_slot to prevent primary from deleting WAL"
    "How do you trigger a manual failover on a standby server to promote it to a primary read-write instance?"
    "What parameter controls the maximum lag allowed or the frequency of WAL shipping between a primary and a standby?"

    # III.27. Monitoring Database Activity
    "/a check the number of active connections on the cluster"
    "/a check the disk space usage of the system"
    "/a get the size of the directory /var/lib/postgresql/18/data"
    "/a query system view to find long-running active queries, their state, and PIDs"
    "/a safely terminate a specific backend process (PID) blocking other queries without restarting"

    # III.28. Reliability and the Write-Ahead Log
    "How does the checkpoints process (checkpoint_completion_target, max_wal_size) flush dirty buffers to disk safely?"
    "What occurs during crash recovery if the database server abruptly loses power or encounters a hard crash?"

    # III.29 & 30 & 31. Logical Replication, JIT, and Regression Tests
    "What are the key differences and limitations of Logical Replication compared to physical streaming replication?"
    "Under what specific cost thresholds or conditions does the PostgreSQL optimizer decide to trigger Just-In-Time (JIT) compilation for queries?"
)

# Récupération dynamique du nombre total de questions
TOTAL_TESTS=${#QUESTIONS[@]}

echo -e "${BOLD}⚡ DÉMARRAGE DE LA SÉRIE DE CRASH-TESTS DE L'AGENCE (${TOTAL_TESTS} TESTS) ⚡${NC}\n"

for i in "${!QUESTIONS[@]}"; do
    echo -e "${GREEN}==================================================================${NC}"
    echo -e "${BOLD}▶️ TEST $((i+1))/${TOTAL_TESTS} : ${QUESTIONS[$i]}${NC}"
    echo -e "${GREEN}==================================================================${NC}"
    
    # APPEL SYNCHRONE
    python agency/orchestrator.py -v <<EOF
${QUESTIONS[$i]}
exit
EOF

    echo -e "\n✅ Test $((i+1)) terminé. Attente de 3 secondes avant le suivant...\n"
    sleep 3
done

echo -e "${BOLD}🏁 Fin de la série de ${TOTAL_TESTS} tests.${NC}"
